name: 1. Create AWS EC2 infrastracture

on:
  workflow_dispatch:
    inputs:
      applicationInstance:
        description: 'Amazon EC2 T2 Instances for application'     
        required: true
        type: 'choice'
        options:
        - t2.micro
        - t2.small
        - t2.medium
        - t2.xlarge
        - t2.2xlarge
      testingToolInstance:
        description: 'Amazon EC2 T2 Instances for testing tool'     
        required: true
        type: 'choice'
        options:
        - t2.micro
        - t2.small
        - t2.medium
        - t2.xlarge
        - t2.2xlarge
        

env:
  AWS_REGION: eu-central-1
  
jobs:
  create:
    name: Create AWS EC2 infrastracture
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: install npm
      run: 'sudo apt update -y && sudo apt install nodejs npm -y'

    - name: Install AWS CDK
      run: 'sudo npm install -g aws-cdk'

    - name: Install Requirements 
      run: 'pip3 install -r requirements.txt'
      
    - name: CDK Synth 
      run: cdk synth

    - name: CDK Deploy
      run: cdk deploy CdkEc2Stack --parameters instanceTypeApplication=${{ github.event.inputs.applicationInstance }} --parameters instanceTypeTestingTool=${{ github.event.inputs.testingToolInstance }} --require-approval never
