name: "3. Connect to testing instance and install Java and Apache Jmeter"

on: workflow_dispatch

jobs:
  connect_ssh:
    name: Connect to testing instance and install JMeter
    runs-on: ubuntu-latest

    steps:
      - name: Install docker
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_TESTING_DNS }}
          username: ec2-user
          port: 22 
          script: |
            sudo yum update -y &&\
             sudo yum install java-17-amazon-corretto -y &&\
                wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz &&\
                  sha512sum apache-jmeter-5.5.tgz &&\ 
                    tar -xf apache-jmeter-5.5.tgz &&\
                      rm apache-jmeter-5.5.tgz
