name: "3. Connect to testing instance and install JMeter"

on: workflow_dispatch

jobs:
  connect_ssh:
    name: Connect to testing instance and install JMeter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Connect to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_TESTING_DNS }}
          REMOTE_USER: ec2-user
          TARGET: /home/ec2-user
